version: "3.1"
services:
  app:
    networks:
      default:
        aliases:
          - app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env